coverage:

  status:
    project:
      default: false  # Disable the default status that measures entire project, it seems to have trouble finding commits to compare against

  notify:
    slack:
      default:
        url: secret:KUlue5nEd+KPP27k+9VunKrC5dPIIl6BZcLRMy0zeoYp9Fa0oGZTynRPiebbYvxfQwHvLC9tZhY88Pkimjgs9WTH+31inFKwAxCQXNid7xe8aUlTgPdn6fyNar3ZLGiKZZiW1EOJPal4ivV0rcnskn91JpS+Cw56rmvLfYZhSvs=
    