language: php

php:
  - '7.0'
  - '7.1'
  - nightly

install:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction

script:
  - mkdir -p tests/logs
  - php vendor/bin/phpunit

after_success:
  - travis_retry php vendor/bin/coveralls -v