shallow_clone: true
clone_folder: C:\projects\slackemon

install:
  - sc config wuauserv start= auto
  - net start wuauserv
  - choco install -y OpenSSL.Light php
  - cd c:\tools\php71
  - copy php.ini-production php.ini
  - echo extension=php_openssl.dll >> php.ini # Required by Composer
  - echo extension=php_mbstring.dll >> php.ini # Required by PHPUnit
  - echo extension_dir="ext" >> php.ini # Enable extensions
  - cd C:\projects\slackemon
  - SET PATH=C:\tools\php71;%PATH%
  - php -r "readfile('http://getcomposer.org/installer');" | php
  - php composer.phar install --prefer-source --no-interaction

test_script:
  - cd C:\projects\slackemon
  - vendor\bin\phpunit.bat

build: off

notifications:
  - provider: Slack
    incoming_webhook:
      secure: Z/sBH2RXNief0BVgo2cazy1KoJMgpA0dZup/E2NMKM9Z40bWyoIK0+yRRJ8HFRxZCNGS+Kri7epYUWDb4QZ8QZHOBKyREESninj1ZM2YT3U=
