shallow_clone: true
clone_folder: C:\projects\slackemon

install:
  - ps: Set-Service wuauserv -StartupType Manual
  - cinst -y php -i
  - cd c:\tools\php71
  - copy php.ini-production php.ini
  - cd C:\projects\slackemon
  - SET PATH=C:\tools\php71;%PATH%
  - php -r "readfile('http://getcomposer.org/installer');" | php
  - php composer.phar install --prefer-source --no-interaction

test_script:
  - cd C:\projects\slackemon
  - vendor\bin\phpunit.bat

notifications:
  - provider: Slack
    incoming_webhook:
      secure: Z/sBH2RXNief0BVgo2cazy1KoJMgpA0dZup/E2NMKM9Z40bWyoIK0+yRRJ8HFRxZCNGS+Kri7epYUWDb4QZ8QZHOBKyREESninj1ZM2YT3U=
