shallow_clone: true
clone_folder: C:\projects\slackemon

install:
  - ps: Set-Service wuauserv -StartupType Manual
  - cinst -y php
  - cd c:\tools\php71
  - copy php.ini-production php.ini
  - cd C:\projects\slackemon
  - SET PATH=C:\tools\php71;%PATH%
  - php -r "readfile('http://getcomposer.org/installer');" | php
  - php composer.phar install --prefer-source --no-interaction

test_script:
  - cd C:\projects\slackemon
  - vendor\bin\phpunit.bat